### PR TITLE
Awesome books: style core elements

### PR DESCRIPTION
**Pull request by lfmnovaes**
In this pull request we:
- Add a new Roboto font.
- Add CSS for styling the form and lists.

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUESTED :recycle:

Hi, @alvarorf  and @lfmnovaes 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
 - The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
-  Git/GitHub flow best practices have been followed.:heavy_check_mark:
- Add, remove and localStorage are working properly:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:
storag5

Changes required :writing_hand: 

  - Kindly, follow github flow, you should have made a dev branch as a default branch to merge after getting approved
  - The live link demo seems to be broken, please fix it.
  
storag6

  Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by lfmnovaes** [comment]
Hi @Emmyn5600, about the requirement. I've just double-checked it and it's working just fine: 
image
https://lfmnovaes.github.io/awesomebooks/

Maybe you were too fast on the review and GitHub didn't finish publishing the page while you were doing the review.

**Comment by mimipeshy** [comment]
### Hello @lfmnovaes  👋,

_This is an additional review as a result of the second opinion request._

According to the [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md), the PR should be raised from `feature` branch to `main` branch. The `feature` branch should be descriptive enough and this is actually a hard requirement but for this milestone, you can work with `dev3` for now. However, in the next milestone, you can consider naming your branches in a more descriptive way. Your live demo works okay and you have met this requirement.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

**Comment by lfmnovaes** [comment]
Thank you very much for the feedback @mimipeshy.
Although I think the PR it's already being raised from `main`, I agree that my feature `branch` isn't descriptive enough. Going to pay more attention to the upcoming branches.

**Review by DeliceLydia — APPROVED** [review]
# Congratulations! 🎉🎉 

## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
